### ISSUE TITLE
Include the website URL in the test mail

### ISSUE THREAD

**Issue by nicomollet** [mailjet/wordpress-mailjet-plugin-apiv3#100]
Hello
Can you please include the website URL in the test mail?

Like:

`Your Mailjet configuration is ok! SSL: Off Port: 25. Sent from www.domain.com`

Kind regards
Nico

**Comment by adamyanliev** [comment]
hi @nicomollet apologies for the huge delay. 

we're developing a new version of the plugin at the moment, and the URL will be included in the test email, once it's released.

Regards,
Atanas
