### ISSUE TITLE
Mailjet Shortcode & Site-Builder Integration & Form Support for non Developers

### ISSUE THREAD

**Issue by MaximPro** [mailjet/wordpress-mailjet-plugin-apiv3#121]
Hi,

When I recently tested Mailjet and I could only include Mailjet Form via Iframe, wich was a Pain, because of CSS Formatting Issues and also the Site Loading Times...

Is there another way to include it into wordpress & woocommerce?
Via API, but also allow to add Mailjet Subscription Form anywhere in Wordpress via Shortcode (& optionally via Widget)
Just for Non-Developers or advanced Users of Mailjet?

**Could you please add this feature in the next Release?**

And also connect to the big Sitebuilders and Platforms with many Users (Divi, Elementor, Visual Composer, etc) and other Instances with main support, also Services like Vimeo, Wistia, Flowplayer or Vooplayer would be amazing.

**Example:**
Divi from Elegant-Themes has already 500,591 Customers (as shown in `https://www.elegantthemes.com`)
and no Mailjet Integration yet?!
![](http://s1.bild.me/bilder/110417/406179606-09-_2018_12-27-04.jpg)

**Example 2:**
Elementor from Elementor.com has 1,000,000+ Users
[](https://elementor.com/pro-v140-form-integrations)
and no Mailjet Integration yet?!
![](https://elementor.com/wp-content/uploads/2017/05/elementor-forms-actions.gif)

This would be big Marketing Step for Mailjet, because most Users probably still don't know Mailjet and only pick your competitors, because of easy Integration. There are Millions to connect with.
Don't miss out on that! This could be probably one of the biggest main steps to your goal to become a leading email marketing platform. ;)

So get your Productsmanager in Contact with all of them and your developers to integrate them ;)

Best regards 
Maxim

**Comment by Jehu** [comment]
+1 for Elementor-Integration and even more important: shortcode

**Comment by mskochev** [comment]
Hello Maxim,

The Mailjet plugin for Wordpress has a built-in subscription widget that works natively in WP and can be included easily like any other widget. Pease have a look: https://www.mailjet.com/guides/wordpress-user-guide/widget-setup/

Regarding including Mailjet in the major sitebuilder platforms - please can you provide more feedback as to what would be the improvement compared to installing the regular Mailjet plugin from the WP plugin directory? https://wordpress.org/plugins/mailjet-for-wordpress/

Kind regards,
Mailjet Plugins team

**Comment by Jehu** [comment]
With Elementor page builder the widget steps for configuration and the language tabs are all visible at once. It's a pain to configure the widget in this case. See screenshot below.

![59ca9983-54ee-4c67-8329-a122f24195c3](https://user-images.githubusercontent.com/650836/50835871-1d3b8300-1358-11e9-8273-338f7a694767.jpg)

**Comment by mskochev** [comment]
OK, I see. Thanks a lot for the feedback.

**Comment by rafaferry** [comment]
+1 for Elementor-Integration and shortcode.

I'm trying to replace my mailchimp forms with mailjet, but on pages that I've created using Elementor that is not possible. The creation of mailjet widgets  just doesn't work inside elementor pages, and there is no shortcode alternative;

It is not viable to recreate all my pages outside Elementor just to add mailjet forms. 

There is any workarround for this now? The only one I can think is codding a form that uses mailJet API, but thats a lot of work in comparison to other mailing solutions.

None of the configuration is clickable on elementor, see the image.
![image](https://user-images.githubusercontent.com/424123/57785628-7fdacc00-7708-11e9-94aa-ff471ea2ab45.png)

**Comment by mdrideout** [comment]
I am also advocating for Elementor integration. I use elementor's form builder and need mailjet to work with it. The MailJet widget is not relevant to my integration needs.

**Comment by zorca** [comment]
+1 for Elementor-Integration

**Comment by DimaMinka** [comment]
+1 for Elementor-Integration

**Comment by ZacJoestar** [comment]
Just faced the Mailjet / Elementor integration problem.
I found a way around that. Just create a Mailjet widget and put it in the sidebar section you want in Appearance > Widgets.
Then in the Elementor editor, place the "sidebar" widget where you want and call the WordPress sidebar section where your Mailjet form is.

Hope i'm clear and this helps ;)

**Comment by mskochev** [comment]
Hi everyone, shortcode for the widget has been implemented and is available in v5.2 of the plugin.
Thanks for your patience.

**Comment by marlonmiller** [comment]
I'm a Elementor Pro user and I realized the there is no integration with mailjet. I suggest to work with site builders companies as there is a huge niche there. As Marketeers normally don't know to code they are using these builders for their web pages and landing pages.

**Comment by mskochev** [comment]
Hi guys, the next plugin release will feature improved widget code that supports the WordPress drag and drop theme customizer. It should be available very soon.

**Comment by flogesell** [comment]
Is there an update yet? As of now, there is no integration? You should really have a look in native suppport for page builders. This is a big improvement over installing yet another plugin just for displaying a subscription form...

**Comment by yeswycan** [comment]
Hi,
We have created a plugin for Mailjet to connect an Elementor Form, because our client need something like that.
Here is the plugin > https://wycan.fr/en/plugin/mailjet-for-elementor-form/
