### ISSUE TITLE
Email confirmation link referre to a localhost URL

### ISSUE THREAD

**Issue by julienfelixweb** [mailjet/wordpress-mailjet-plugin-apiv3#150]
When a subscriber click on the confirmation URL in the confirmation email, it redirects to an old dev local URL of the website.

**Comment by mskochev** [comment]
Hello, we'll check that ASAP

**Comment by mskochev** [comment]
@julienfelixweb please can you have a look in your WordPress admin -> General settings -> Site Address what is the URL that is stored in this field? We use this URL to redirect the user to the site.

**Comment by julienfelixweb** [comment]
Yes, that's the first thing I checked, this is correct but the URL in the mail is different. Are you storing it somewhere ?

**Comment by mskochev** [comment]
The problem has been identified. A fix is on its way. Thanks for reporting it and apologies for the inconvenience.

**Comment by mskochev** [comment]
The update has been uploaded on WordPress.org. Please update to v. 5.0.7. Keep in touch in case the problem persists.

**Comment by julienfelixweb** [comment]
The version 5.0.7 has solved the problem, thanks a lot for your rapidity and your help !
