### ISSUE TITLE
Fatal Error Wordpress 5.2

### ISSUE THREAD

**Issue by julienfelixweb** [mailjet/wordpress-mailjet-plugin-apiv3#193]
I do have a strange Fatal Error with the Mailjet Plugin…

Fatal error: Uncaught Error: Call to undefined method Mailjet\Client::addRequestOption() in […]wp-content/plugins/mailjet-for-wordpress/src/includes/MailjetApi.php:37 Stack trace: #0 […]wp-content/plugins/mailjet-for-wordpress/src/includes/MailjetApi.php(219): MailjetPlugin\Includes\MailjetApi::getApiClient() #1 […]wp-content/plugins/mailjet-for-wordpress/src/includes/MailjetSettings.php(189): MailjetPlugin\Includes\MailjetApi::isValidAPICredentials() #2 […]wp-content/plugins/mailjet-for-wordpress/src/includes/MailjetSettings.php(93): MailjetPlugin\Includes\MailjetSettings->addMailjetActions() #3 […]wp-includes/class-wp-hook.php(286): MailjetPlugin\Includes\MailjetSettings->mailjet_settings_init('') #4 […]wp-content/plugins/mailjet-for-wordpress/src/includes/MailjetApi.php on line 37

**Comment by mskochev** [comment]
Thanks for the report. We are working on it.

**Comment by julienfelixweb** [comment]
Hi mskochev,
The issue was coming form me. I failed to update some code on this project and the API was not working correctly. I fixed it.

Sorry and thanks

**Comment by julienfelixweb** [comment]
I was using old option's identifiant to call the API credentials…

**Comment by mskochev** [comment]
Thanks for the feedback :) I'm glad the problem is resolved.
