### ISSUE TITLE
Messaging out of visible area after submiting form

### ISSUE THREAD

**Issue by rafaferry** [mailjet/wordpress-mailjet-plugin-apiv3#195]
Hello,

I'm migrating from Mailchimp to mailjet, and found some issues while setting up my subscription form. 

My subscription form is at the bottom of each post. When the user submits the form, the page is refreshed, so the vertical scroll is set at 0, and the user can't see the message that I've configurated through the plugin.

I think that this submit could be done though AJAX

Another option is adding a css class to the message container, so I could style it as fixed and show at the top of my website. 

There is already a [PR](https://github.com/mailjet/wordpress-mailjet-plugin-apiv3/pull/194)  with the css class. When are you planning a new release with this? 

Thank you!

**Comment by mskochev** [comment]
Hello, the pull request has been merged and released in v5.1.1 of the plugin. You can get the latest version form here or from the WordPress plugins directory: https://wordpress.org/plugins/mailjet-for-wordpress/
