### ISSUE TITLE
perf: avoid doing a SQL update call on each page load

### ISSUE THREAD

**Issue by rayrutjes** [mailjet/wordpress-mailjet-plugin-apiv3#258]
Currently, this code is triggered on every run: 
https://github.com/mailjet/wordpress-mailjet-plugin-apiv3/blob/master/src/includes/Mailjet.php#L84

As a result, we end up with 1 useless SQL UPDATE query per PHP run.

Do you think we could remove that?

**Comment by mskochev** [comment]
Hello, thanks for the suggestion. Indeed it is redundant request and we will remove it.

**Comment by mskochev** [comment]
The fix will be available in the next plugin release.
