### ISSUE TITLE
perf: do not load JS frontend script if not useful

### ISSUE THREAD

**Issue by rayrutjes** [mailjet/wordpress-mailjet-plugin-apiv3#262]
Currently the plugin enqueues a frontend JS script adding a useless HTTP roundtrip.

Would it be possible to remove that when detecting it is not used?

I guess this is only used if we use some kind of frontend form. 

Here is what currently needs to be done to remove that script:

```php
<?php
function dequeue_mailjet_script() {
	wp_dequeue_script( 'ajaxHandle' );
}
add_action( 'wp_print_scripts', 'dequeue_mailjet_script', 100 );
```

Note that `ajaxHandle` isn't a really good handle name. It would be better to add a namespace before to avoid conflicts with other plugins.

**Comment by mskochev** [comment]
Hi, thanks for reporting this issue. It will be fixed in the next plugin release.
