### ISSUE TITLE
Double opt-in

### ISSUE THREAD

**Issue by Colir** [mailjet/wordpress-mailjet-plugin-apiv3#265]
Hello.
I use your plugin in conjunction with the plugin CF7 to Mailjet (https://fr.wordpress.org/plugins/cf7-to-mailjet/) to be able to send subscriber to different contact list according to the form they submit.

My issue is this : how to force the official mailjet plugin to use double opt-in when subscribing ?

Didn't find this option on the plugin admin page, or on the Mailjet admin panel.

Must i do this programmatically ?

Thanks you very much, and thanks Mailjet for you really nice mailing system (love the mjml)

**Comment by oleksandr-mykhailenko** [comment]
Hello @Colir 
Thanks for reporting this. Issues was resolved in our new version of plugin (v 5.3.6)
