### ISSUE TITLE
Composer installation issue

### ISSUE THREAD

**Issue by eartisan-uk** [mailjet/wordpress-mailjet-plugin-apiv3#270]
Could someone kindly explain why can't I use "composer require wpackagist-plugin/mailjet-for-wordpress" to install this using WordPress Packagist? When I try that, it installs downloads pretty much every version of it but it doesn't install it as a plugin so it doesn't become visible under Plugins section within the dashboard. Thanks!

**Comment by mb79** [comment]
Same error for me. The composer package of the 5.2.1 version is wrong, it return the root svn project and not the trunk. See the differences :
- https://plugins.svn.wordpress.org/mailjet-for-wordpress/tags/5.2/
- https://plugins.svn.wordpress.org/mailjet-for-wordpress/tags/5.2.1/

**Comment by jasperf** [comment]
Yeah, same here. Had to go for basic plugin installation instead of using composer. And that is a real bummer.

**Comment by atoupet-toki** [comment]
Same probleme here :(

**Comment by Pavlico** [comment]
Tested, plugin is installing fine with composer and it is visible on plugin section in dashboard. Do you guys still have this problem?

**Comment by eartisan-uk** [comment]
@Pavlico Thanks for the update. Yes, it seems to be working fine now so I'm closing this thread.
