### ISSUE TITLE
Wrong Widget ID in  __CONFIRM_URL__  of confirm subscription email

### ISSUE THREAD

**Issue by fine-G** [mailjet/wordpress-mailjet-plugin-apiv3#272]
I use the Plugin with Widgets in 4 dynamic_sidebars. In each is one widget, each attached to an other list. With the current versions of the plugin the CONFIRM_URL contains not the widget_id send from the form in the widget_id hidden field. With this issue it is not possible to subscribe in the right list.

I change my code and run the widgets with a do_sortcode(…). the result is the same. On the page is the right form is shown, with the right id in the widget_id hidden fields and form name. but again the widget id in __CONFIRM_URL__ is wrong.

Actually I have widget IDs 3,4,5,6,7 but in the __CONFIRM_URL__ is the ID 1

**Comment by Pavlico** [comment]
Hi @fine-G can you provide my with step by step guidance to reproduce issue, i tried to redo your scenario and it looks to me that confirm Url has different id for each widget it came from.

**Comment by Pavlico** [comment]
Could not reproduce, no update on issue from creator
