### ISSUE TITLE
Error "No valid value" adding the widget to side bar [WP-5.4]

### ISSUE THREAD

**Issue by Danixu** [mailjet/wordpress-mailjet-plugin-apiv3#274]
Hello,

My question seems to be about the Wordpress 5.4 and PHP 7.4 compatibility, because maybe the problem is that (the plugins only was tested until WP 5.3).

My problem is that I've installed the latest version of the plugin, I've configured all the options and when I want to add a Widget to my side bar then it fails just saying "No valid value". 

Adding the widget I've got this error:
`2020/06/04 20:08:27 [error] 21691#21691: *138673 FastCGI sent in stderr: "PHP message: PHP Notice:  Trying to access array offset on value of type bool in /server/project/xxxxxx.com/www/wp-includes/class-wp-customize-widgets.php on line 1486PHP message: PHP Notice:  Undefined index: wp_mailjet_subscribe_widget-4 in /server/project/xxxxxx.com/www/wp-includes/class-wp-customize-widgets.php on line 1501" while reading response header from upstream, client: 46.25.49.202, server: www.xxxxxx.com, request: "POST /wp-admin/admin-ajax.php HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "www.xxxxxx.com", referrer: "https://www.xxxxx.com/wp-admin/customize.php?autofocus%5Bpanel%5D=widgets&return=%2Fwp-admin%2Fwidgets.php"`

And after pressing the Apply button:
`2020/06/04 20:09:41 [error] 21691#21691: *138673 FastCGI sent in stderr: "PHP message: PHP Notice:  Trying to access array offset on value of type bool in /server/project/xxxxxx.com/www/wp-includes/class-wp-customize-widgets.php on line 1486PHP message: PHP Notice:  Undefined index: wp_mailjet_subscribe_widget-4 in /server/project/xxxxxx.com/www/wp-includes/class-wp-customize-widgets.php on line 1501" while reading response header from upstream, client: xx.xx.xx.xx, server: www.xxxxxx.com, request: "POST /wp-admin/admin-ajax.php HTTP/2.0", upstream: "fastcgi://unix:/run/php/php7.4-fpm.sock:", host: "www.xxxxxx.com", referrer: "https://www.xxxxxx.com/wp-admin/customize.php?autofocus%5Bpanel%5D=widgets&return=%2Fwp-admin%2Fwidgets.php"`

Someone knows how to solve this error?.

Thanks!

**Comment by Pavlico** [comment]
Hi @Danixu do you still have issues, I downgraded wordpress to 5.4.1 and with php 7.4 issue does not exist.

**Comment by Danixu** [comment]
I am not sure. I had to change to another tool and I am not using this widget now.
