### ISSUE TITLE
Start scenario on purchase

### ISSUE THREAD

**Issue by lionelsellam** [mailjet/wordpress-mailjet-plugin-apiv3#275]
Hi,

I'm sorry but i begin to use your plugin which is excellent work, but i had a question of a feature that i don't know if it's possible with your plugin.

I need that when a customer buy my product on my woocommerce, that it begins a scenario that i previously prepared on mailjet.

Let's say he/she buy and then it should send him/her a first mail, after a day another one , etc etc ..

I don't know if that's possible. If you could help me with that i would be very glad. Thank you very much !

**Comment by kriefsacha** [comment]
I also would like to know about this. Some news please ???

**Comment by oleksandr-mykhailenko** [comment]
For now I do not have such information, but in the future it could be done
