### ISSUE TITLE
⚠ [FATAL ERROR] WP 5.4.2

### ISSUE THREAD

**Issue by Prometee** [mailjet/wordpress-mailjet-plugin-apiv3#279]
```
PHP Fatal error: require_once(): Failed opening required ‘[…]/wp-includes/PHPMailer/PHPMailer.php’ in […]/wp-content/plugins/mailjet-for-wordpress/src/includes/MailjetMail.php on line 26
```

The new PHPMailer is not yet updated in WordPress 5.4.2 so this plugin need to take care of an incoming BC break due to the update of PHPMailer.

WP 5.4
http://core.svn.wordpress.org/branches/5.4/wp-includes/class-phpmailer.php
WP 5.5
http://core.svn.wordpress.org/branches/5.5/wp-includes/PHPMailer/

The error was caused by #278

**Comment by speckz** [comment]
Is this why it was removed from https://wordpress.org/plugins/mailjet-for-wordpress/?

> This plugin has been closed as of July 28, 2020 and is not available for download. This closure is temporary, pending a full review.

**Comment by Prometee** [comment]
Perhaps ... !

**Comment by nicomollet** [comment]
Indeed it was removed because of this issue.
Mailjet needs to do something quickly.

**Comment by ngarnier** [comment]
Hey everyone, thanks for reporting. We've deleted the 5.2.2 version and reset the stable version 5.2.1 so installing via the Github zip should still work. 

We're working with the WP team to get our plugin back live ASAP.

Thanks for your understanding and patience.

**Comment by ngarnier** [comment]
Hi everyone, 

We're back online https://wordpress.org/plugins/mailjet-for-wordpress/! 

Sorry for the trouble and thanks again for your patience.

**Comment by nicomollet** [comment]
@ngarnier Great!

Still, I hope you can look at all the issues 5.2.0 and 5.2.1 had the past months.
https://wordpress.org/support/plugin/mailjet-for-wordpress/
Issues with the settings page, the frontend javascript errors, problems with composer.

Thank you
