### ISSUE TITLE
Translation problem on WooCommerce order received (notice)

### ISSUE THREAD

**Issue by jblouvet** [mailjet/wordpress-mailjet-plugin-apiv3#289]
**Description of the problem :**
I have added the checkbox field to subscribe to the newsletter at checkout.
After submission, on order received template, Mailjet adds a notice to warn about double opt-in confirmation sent by mail.
That message is not translated (English only).
The string is not the .pot file (checked in Loco Translate), I guess it comes as an API response.

Also, that notice is added in a meh way : ```<br><br><i>message<I>``` which makes it impossible to properly handle in css.

**Comment by Pavlico** [comment]
Hi @jblouvet do you still have issue or is it fixed?

**Comment by Pavlico** [comment]
No answer, closing.
