### ISSUE TITLE
wp_nav_menu / header problem with custom thank-you-template

### ISSUE THREAD

**Issue by fine-G** [mailjet/wordpress-mailjet-plugin-apiv3#291]
We have a custom thank-you-template with the full header the website including the wp_nav_menu.
the menu works well on all pages, but on the thank you page all cpt item are lost!

Disabled all not required Plugins and everything not required from the functions.php and also from the header etc. But it is still the same the CPTs are not showing up.

I added the CPT Items to an other menu but, is the same on the thank-you page, the items are not there.

I think that maybe a query in the plugin is not properly reseted, or there are to many or one disturbing argument in the ULR?

 for a test I add the Nav code in the WP_Mailjet_Subscribe_Widget.php with the same result: I got the nav but without CPTs

`$newsletterRegistration = Mailjeti18n::getTranslationsFromFile($locale, 'Newsletter Registration');
            $congratsSubscribed = Mailjeti18n::getTranslationsFromFile($locale, 'Congratulations, you have successfully subscribed!');

          //  $thankYouPageTemplate = apply_filters('mailjet_thank_you_page_template', plugin_dir_path(__FILE__) . 'templates' . DIRECTORY_SEPARATOR . 'thankyou.php');

          //  include($thankYouPageTemplate);
            
		wp_reset_postdata();
		wp_reset_query();
		$primary_menu_args = array(
			'theme_location'  => 'main_menu',
			'container'       => '<ul id="primary_menu">',
			'container_class' => 'main_menu',
			'container_id'    => 'main_menu',
			'menu_class'      => 'primary_menu menu',
			'menu_id'         => 'primary_menu',
			'echo'            => false,
			'before'          => '',
			'after'           => '',
			'link_before'     => '',
			'link_after'      => 0,
			'fallback_cb'	=> 'main_menu',
		);
	$primary_menu = wp_nav_menu( $primary_menu_args ); 			
	
	var_dump($primary_menu);
            
            die;
        }`

We use the cutest WP and Plugin Versions
Can you help me?

**Comment by Pavlico** [comment]
Hi @fine-G , have you managed to fix issue ?

**Comment by Pavlico** [comment]
Cant reproduce, no response. Closing
