### ISSUE TITLE
Is it possible to use different mailjet lists in different contact form 7 forms?

### ISSUE THREAD

**Issue by luxio** [mailjet/wordpress-mailjet-plugin-apiv3#293]
Is it possible to use different mailjet lists in different contact form 7 forms?
Currently I can only select one mailjet list in the contact form 7 settings:

<img width="716" alt="Bildschirmfoto 2021-03-01 um 11 47 05" src="https://user-images.githubusercontent.com/1497217/109486997-ebc82900-7a83-11eb-936a-be5d7eccd4e6.png">

**Comment by Pavlico** [comment]
it is not possible right know
