### ISSUE TITLE
Feature Request

### ISSUE THREAD

**Issue by dev-cb** [mailjet/wordpress-mailjet-plugin-apiv3#319]
Would be great to change the design of the opt-in email which is located in `/src/templates/confirm-subscription-email.php` with a setting in the WP dashboard.

AND

It would be great to adjust the thank you page target instead of using the `/src/templates/thankyou.php` default template.

**Comment by oleksandr-mykhailenko** [comment]
Hello @dev-cb 
Thank you for your ideas. I send your request to another department that will consider your request
