### ISSUE TITLE
Connexion aléatoire

### ISSUE THREAD

**Issue by sigmike** [mailjet/wordpress-mailjet-plugin-apiv3#32]
Bonjour,

J'ai un problème similaire à #4 qui se manifeste surtout sur Mac.

Sur Safari sur Mac rien n'apparait quand je clique sur "Campagnes", "Listes" ou "Statistiques". Sur le même poste mais avec Firefox ça fonctionne bien.

Sur un autre poste sur Firefox et toujours sur Mac, l'écran de connexion Mailjet apparait.

Sur Firefox sur Linux aucun problème.

**Comment by aneliyaB** [comment]
Bonjour Michaël,

Pourriez-vous vérifier, svp, vous paramètre de connexion (API/Secret key) et cliquer sur "Sauvegarder" pour régénérer un nouveau token sur Safari/Firefox et tester ensuite?

Merci,
L’équipe Mailjet

**Comment by sigmike** [comment]
Bonjour,

J'ai vérifié les paramètres API et Secret, cliqué sur sauvegarder, et le problème est toujours le même.

**Comment by aneliyaB** [comment]
Bonjour Michaël,

Nous ne sommes pas en mesure de reproduire le problème (testé sous Safari/Firefox sur Mac). Pourriez vous nous envoyer votre API key a plugins@mailjet.com ? 

Merci,
L’équipe Mailjet

**Comment by sigmike** [comment]
Bonjour,

Le problème n'est malheureusement pas réglé. Quand je clique sur "Campagnes" un requête est faite à votre serveur et Safari indique une erreur "Failed to load resource: too many HTTP redirects".

Et effectivement quand je demande cette même URL avec curl j'ai comme réponse une redirection HTTP vers la même URL.

**Comment by aneliyaB** [comment]
Bonjour Michaël,

Est-ce que vous recevez cette erreur chaque fois que vous cliquer sur "Campagnes" ou bien c'est aléatoire? Est-ce que vous pouvez accéder les "Contacts" et "Stats"?

Merci,
L’équipe Mailjet

**Comment by sigmike** [comment]
Bonjour,

J'ai cette erreur à chaque fois. Les pages "Statistiques" et  "Liste" provoquent la même erreur.
