### ISSUE TITLE
class "MailjetPlugin\Includes\MailjetMail" not found

### ISSUE THREAD

**Issue by horieva** [mailjet/wordpress-mailjet-plugin-apiv3#332]
Hello there, and greetings from Ukraine.

We have a problem with Mailjet Transactional Mails: when I try to send test mail from the plugin options I see that error: 

```
Fatal error: Uncaught Error: call_user_func_array(): Argument #1 ($callback) must be a valid callback, class "MailjetPlugin\Includes\MailjetMail" not found
in /var/www/html/wp-includes/class-wp-hook.php on line 307

Call stack:

WP_Hook::apply_filters()
wp-includes/plugin.php:191
apply_filters()
wp-includes/formatting.php:5984
wp_staticize_emoji_for_email()
wp-includes/class-wp-hook.php:307
WP_Hook::apply_filters()
wp-includes/plugin.php:191
apply_filters()
wp-includes/pluggable.php:200
wp_mail()
wp-content/plugins/mailjet-for-wordpress/src/includes/MailjetMail.php:80
MailjetWp\M\I\MailjetMail::sendTestEmail()
wp-content/plugins/mailjet-for-wordpress/src/includes/SettingsPages/EnableSendingSettings.php:212
MailjetWp\M\I\S\EnableSendingSettings::mailjet_sending_settings_page_html()
wp-includes/class-wp-hook.php:307
WP_Hook::apply_filters()
wp-includes/class-wp-hook.php:331
WP_Hook::do_action()
wp-includes/plugin.php:476
do_action()
wp-admin/admin.php:259
```

We use Litespeed and PHP 8.1

Plugin installed from WP Repository and has version 5.2.21.

**Comment by pablodiloreto** [comment]
The same problem for me. Plugin (last version) installed in several sites with WP 6.0.1. Any update?

**Comment by oleksandr-mykhailenko** [comment]
@horieva Hello, is this problem only for transasctional emails ?

**Comment by horieva** [comment]
@oleksandr-mykhailenko I use only transactional emails.

**Comment by oleksandr-mykhailenko** [comment]
@horieva I see, we will check today this part. Thank you for your message. Today, in the evening I will post results

**Comment by oleksandr-mykhailenko** [comment]
Hello @horieva So I've update plugin. Right now it works with php 8.1. There was a problem with namespace definition. Thank you

Stay safe and my greetings from Dnipro :)
