### ISSUE TITLE
Plugin Mailjet for wordpress closed on wordpress.org

### ISSUE THREAD

**Issue by etruel** [mailjet/wordpress-mailjet-plugin-apiv3#336]
![image](https://user-images.githubusercontent.com/3663229/199612528-4533b953-69c0-4f36-9a01-3e32469fe927.png)

Please give an update of this.

Thank you

**Comment by oleksandr-mykhailenko** [comment]
Hello @etruel We are working on it. It is temporary issue. We chatting with wordpress. This issue will be resolved today

**Comment by etruel** [comment]
That's great. Thanks for the update.

**Comment by nicomollet** [comment]
If only you were notified about the .GIT folder issue sooner. /sarcasm.

Oops I did that in September (https://wordpress.org/support/topic/plugin-size-is-now-100m/). 
Oops I also created a support ticket but your support team didn't even believe me in the first place.

**Comment by frenchcharly** [comment]
> Hello @etruel We are working on it. It is temporary issue. We chatting with wordpress. This issue will be resolved today

18 days later, any updates ?

**Comment by oleksandr-mykhailenko** [comment]
> > Hello @etruel We are working on it. It is temporary issue. We chatting with wordpress. This issue will be resolved today
> 
> 18 days later, any updates ?

They are haven't checked plugin yet. We made all needed changes. We keep track this and I believe, soon it will be resolved.

**Comment by oleksandr-mykhailenko** [comment]
Plugin was opened
