### ISSUE TITLE
plugin error after update

### ISSUE THREAD

**Issue by buzucan** [mailjet/wordpress-mailjet-plugin-apiv3#373]
Hello, I have a problem with the new update from the plugin. The error message is:
![image](https://github.com/user-attachments/assets/e139d2de-3246-4387-91fc-42abd21a7304)

Before the update all was fine.

Here is the log:

2024/09/09 07:54:31 [error] 648#648: *113525 FastCGI sent in stderr: "PHP message: PHP Fatal error:  Uncaught Error: Class "MailjetWp\MailjetPlugin\Front\Mailjet" not found in /var/www/mariuscucu.ro/htdocs/wp-content/plugins/mailjet-for-wordpress/src/front/MailjetPublic.php:84
Stack trace:
#0 /var/www/mariuscucu.ro/htdocs/wp-includes/class-wp-hook.php(324): MailjetWp\MailjetPlugin\Front\MailjetPublic->enqueue_scripts()
#1 /var/www/mariuscucu.ro/htdocs/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#2 /var/www/mariuscucu.ro/htdocs/wp-includes/plugin.php(517): WP_Hook->do_action()
#3 /var/www/mariuscucu.ro/htdocs/wp-includes/script-loader.php(2263): do_action()
#4 /var/www/mariuscucu.ro/htdocs/wp-includes/class-wp-hook.php(324): wp_enqueue_scripts()
#5 /var/www/mariuscucu.ro/htdocs/wp-includes/class-wp-hook.php(348): WP_Hook->apply_filters()
#6 /var/www/mariuscucu.ro/htdocs/wp-includes/plugin.php(517): WP_Hook->do_action()
#7 /var/www/mariuscucu.ro/htdocs/wp-includes/general-template.php(3065): do_action()
#8 /var/www/mariuscucu.ro/htdocs/wp-content/them" while reading response header from upstream, client: 2a02:2f01:7307:3700:799c:521e:3fb6:3726, server: mariuscucu.ro, request: "GET / HTTP/1.1", upstream: "fastcgi://unix:/var/run/php/php83-fpm.sock:", host: "mariuscucu.ro"

**Comment by solracsf** [comment]
Fix at https://github.com/mailjet/wordpress-mailjet-plugin-apiv3/pull/374

**Comment by oleksandr-mykhailenko** [comment]
Hello @solracsf 
Thank you for this catch! Already merge this. Updating plugin on the marketplace
