### ISSUE TITLE
Problème clé api / connexion ?

### ISSUE THREAD

**Issue by support-klub** [mailjet/wordpress-mailjet-plugin-apiv3#4]
Bonjour,

Nous constatons des bugs réguliers depuis plus d'un mois avec le plugin Mailjet destiné à Wordpress et ceci sur deux sites, un en version 4.0 de Wordpresse et un en version 3.9 .Voici les bugs constatés :

Le problème se situe surtout sur "Lists" et "Campaigns" lorsqu'on est connecté à l'interface de gestion du site Wordpress. Une fois sur deux les informations ne sont pas chargées et une boîte de connexion apparaît (cf. screenshot). C'est comme si les informations de la clé API et la clé secrète était effacée.

Si en parallèle dans un nouvel onglet on se connecte sur l'interface Mailjet (https://fr.mailjet.com/signin), le problème ne se pose quasiment plus mais nous ne souhaitons pas donner ces accès à nos utilisateurs et sans se connecter à Mailjet ils ne parviennent pas à gérer leurs contacts et leurs newsletter via le back-office Wordpress.

Pouvez-vous nous dire quel est le problème ? Comment le résoudre ?

![bug-mailjet-signin](https://cloud.githubusercontent.com/assets/8780060/4273242/fe04e30e-3ce8-11e4-881e-c85addcd43df.jpg)

**Comment by aneliyaB** [comment]
Bonjour Sylvain,

Merci de préciser quel avatar vous voudriez modifier - votre avatar GitHub?

Cordialement,

L’équipe de Mailjet

**Comment by vincentdcom** [comment]
Bonjour,

J'ai le même problème que support-klub, et un ticket ouvert et non-résolu depuis un mois via le support Mailjet (TICKET N° 272570).

Pouvez-vous m'aider à le résoudre ?

**Comment by ddxb** [comment]
On va regarder ça. Merci.

--
Stephen Bauer

**Comment by vincentdcom** [comment]
Bonjour, 

ce n'était probablement pas exactement le même problème.

Apparemment chaque utilisateur (IP différente) doit enregistrer les paramètres (clé API et clé secrète) pour générer un token de sécurité lié à l'IP utilisée.

**Comment by sylvain223** [comment]
L'avatar que je vous parle ce pour wordpress,

bien cordialement,
sylvain.

**Comment by sylvain223** [comment]
comment fonctionne
l'adresse email github,
je ne trouve pas l'accès de cette adresse.

**Comment by yasen-mailjet** [comment]
Wordpress use avatars from https://en.gravatar.com/
