### ISSUE TITLE
Error. $_GET['token'] param conflict

### ISSUE THREAD

**Issue by VovikeMS** [mailjet/wordpress-mailjet-plugin-apiv3#56]
Hello. I have been used your useful plugin. But i started integrate some payment API, and have error by 'token' variable. 
My payment gateway use some redirect link with token verification. Your plugin see this token and try to use it, but it token not for Mailjet, its for my payment gateway.
Link: https://github.com/mailjet/wordpress-mailjet-plugin-apiv3/blob/master/mailjet-widget.php#L508

Can you change name of this parameter, for ex: 'token' => 'mj_token'?
I will be very happy :).
Thanks.

**Comment by yasen-mailjet** [comment]
Hello VovikeMS, thank you for reporting the issue. We will fix it as soon as possible.

**Comment by VovikeMS** [comment]
Thanks lot. I wait for your fixes. Please, notify me when you done.
