### ISSUE TITLE
Undefined index: titlefr  in mailjet-widget.php

### ISSUE THREAD

**Issue by Abdou00** [mailjet/wordpress-mailjet-plugin-apiv3#58]
Hello,
I install the plugin [ v3 API ] Mailjet for WordPress and I called with the following code in my page: `<? php the_widget ( ' WP_Mailjet_Subscribe_Widget '); ? >` But when I go to that page I have the following errors:
Notice: Undefined index: titlefr in /var/www/html/wp-content/plugins/wordpress-mailjet-plugin-apiv3/mailjet-widget.php on line 608

Notice: Undefined index: list_idfr in /var/www/html/wp-content/plugins/wordpress-mailjet-plugin-apiv3/mailjet-widget.php on line 609

Notice: Undefined index: button_textfr in /var/www/html/wp-content/plugins/wordpress-mailjet-plugin-apiv3/mailjet-widget.php on line 610

**Comment by mskochev** [comment]
Not relevant anymore, so closing this issue.
