### ISSUE TITLE
Too many external calls

### ISSUE THREAD

**Issue by Rahe** [mailjet/wordpress-mailjet-plugin-apiv3#65]
Hello,

Your plugin is generating too much external calls, yesterday your API was down I guess so it responded with 250 sec, can you use some cache, use asynchronic calls, keep the credentials for the account or something else ? This is a regular problem with this plugin 
<img width="1377" alt="mailjet" src="https://user-images.githubusercontent.com/1007502/28107609-c45b9922-66e8-11e7-9dac-2df112b11e7f.png">

And the API is too slow, it responds in 350ms and is called at almost everypage call 
<img width="362" alt="mailjet-calls" src="https://user-images.githubusercontent.com/1007502/28107661-f9440e30-66e8-11e7-8277-43b9f8a60983.png">

For the last 7days 96% of external calls are made by mailjet, at 129 calls per minute.

Is this possible to lower the api calls ? or using a lower timeout for the external calls ?

**Comment by mskochev** [comment]
Hello Rahe,

Thanks for your feedback. We will investigate the issue that you have reported.

Best regards,
Mailjet Plugins Team

**Comment by mskochev** [comment]
Hello Rahe,

Please can you check which version of the plugin you are currently using? An improvement reducing the number of API calls was deployed with v. 4.1.15.

Also, have you identified which API calls slow down your site?

Thanks!

**Comment by Rahe** [comment]
Hi,

We are using the version 4.1.8, when no credentials have been set the API is called on every backend page.
The slow queries are when the API is called to get the available API for the account (v1 or V3).

We will check the update of the plugin ;)

Nicolas,

**Comment by mskochev** [comment]
Hello Rahe, thanks for your feedback. This is exactly the issue that has been resolved in v. 4.1.15. Please keep us posted if after updating you still experience slow performance.

Best regards,
Mailjet Plugins Team

**Comment by Rahe** [comment]
Hello,

I think the main issue behind this is that the plugin have no real timeout on the external queries, so when your services are down the website is slow.
Is there any reasonable timeout applyed in the new version ?

**Comment by mskochev** [comment]
The credentials are cached, so no further API calls are made, hence no timeout is required.

**Comment by mskochev** [comment]
I'm closing this thread as the issue should be resolved in the current plugin version. If there is similar issue with the current version, please open a new thread and we will be happy to assist you.
