### ISSUE TITLE
Add hidden field

### ISSUE THREAD

**Issue by Geam** [mailjet/wordpress-mailjet-plugin-apiv3#97]
Hello,
Is-it possible to add hidden field ?

Currently, I can add fields and set a placeholder. I would like to be able to add the same fields but set the value (with different value per language) and set the field as hidden.
Maybe if the field is set as hidden use the placeholder as the value would not require too much modification ?

**Comment by adamyanliev** [comment]
hey @Geam ,

Just to let you know that this was added to the new version of the plugin. It's now in beta, you can download this release to test it, if you want: https://github.com/mailjet/wordpress-mailjet-plugin-apiv3/releases/tag/v5.0.0-beta2

It should be released in January.

Regards,
Atanas

**Comment by mskochev** [comment]
The hidden fields are now available in the official plugin release so I'm closing this request.
